### ISSUE TITLE
Pattern table fetch has an incorrect mask.

### ISSUE THREAD

**Issue by jc-SpaceXp** [mwillsey/NES#1]
You have an incorrect mask for your pattern table fetch: https://github.com/mwillsey/NES/blob/master/ppu.c#L119  

Mask for p->scanline should be 7 not 8.

**Comment by mwillsey** [comment]
Thanks for checking it out, I hope you found it helpful.

I'm not maintaining this anymore, but I'll definitely leave it up.

**Comment by jc-SpaceXp** [comment]
It was very helpful actually! Thanks for keeping it up.
